using System;
using System.Globalization;
using System.Text;

namespace NXSG.Backend
{
    // Three edge strips approximate a silhouette fin per source triangle. Mesh adjacency is unavailable,
    // so the view-grazing factor suppresses most internal edges while retaining bounded geometry cost.
    internal static class FurFinShader
    {
        static string Num(double value) { return AdvancedShaderEmitter.NumExpr(value); }

        public static string Pass(string rootColor, string tipColor, string length, string density, string thickness, string mask, string groom, string time, double taper, double gravity, double windStrength, double windSpeed, double windScale, double rimStrength, double finOpacity, bool receiveShadows = true)
        {
            var b = new StringBuilder();
            b.Append("Pass {\nName \"FurFins\"\nTags { \"LightMode\"=\"ForwardBase\" }\nCull Off\nZWrite Off\nBlend SrcAlpha OneMinusSrcAlpha\nCGPROGRAM\n#pragma target 4.5\n#pragma vertex vertFurFin\n#pragma geometry geomFurFin\n#pragma fragment fragFurFin\n#pragma multi_compile_instancing\n#pragma multi_compile_fwdbase nolightmap nodirlightmap nodynlightmap novertexlight\n");
            b.Append("struct NXFinInput { NXInput data; float3 furGradU:TEXCOORD18; float3 furGradV:TEXCOORD19; };\n");
            b.Append("NXInput vertFurFin(NXApp v) { UNITY_SETUP_INSTANCE_ID(v); NXInput baseInput=NX_Make(v); NXInput input=baseInput; float finLength=max(0,(").Append(length).Append(
                ")); float3 finGroom=").Append(groom).Append("; float finTime=").Append(time).Append("; float3 finWind=float3(sin(finTime*").Append(Num(windSpeed)).Append("+v.vertex.x*").Append(Num(windScale)).Append("),0,cos(finTime*").Append(Num(windSpeed)).Append("+v.vertex.z*").Append(Num(windScale)).Append("))*").Append(Num(windStrength)).Append("; v.vertex.xyz += v.normal*finLength + finGroom*finLength + finWind*finLength + float3(0,-").Append(Num(gravity)).Append("*finLength,0); NXInput tipInput=NX_Make(v); NXInput o=baseInput; o.originalLocal=baseInput.originalLocal; o.originalWs=baseInput.originalWs; o.sourceUV=float2(finLength,0); o.screenPos.xyz=tipInput.ws; UNITY_INITIALIZE_VERTEX_OUTPUT_STEREO(o); return o; }\n");
            b.Append("float NX_FurFinHash(float3 p) { return frac(sin(dot(p,float3(17.13,41.71,93.17)))*43758.5453); }\n");
            b.Append("void NX_EmitFurFin(NXInput a, NXInput b, float edgeSeed, float3 gu, float3 gv, inout TriangleStream<NXFinInput> stream) { float3 p0=a.ws; float3 p1=b.ws; float3 q0=a.screenPos.xyz; float3 q1=b.screenPos.xyz; NXInput o=a; o.pos=UnityWorldToClipPos(p0); o.ws=p0; o.screenPos=ComputeGrabScreenPos(o.pos); o.wireBary=float3(0,0,edgeSeed); UNITY_INITIALIZE_VERTEX_OUTPUT_STEREO(o); TRANSFER_SHADOW_WPOS(o,o.ws); { NXFinInput f; f.data=o; f.furGradU=gu; f.furGradV=gv; stream.Append(f); } o=b; o.pos=UnityWorldToClipPos(p1); o.ws=p1; o.screenPos=ComputeGrabScreenPos(o.pos); o.wireBary=float3(1,0,edgeSeed); UNITY_INITIALIZE_VERTEX_OUTPUT_STEREO(o); TRANSFER_SHADOW_WPOS(o,o.ws); { NXFinInput f; f.data=o; f.furGradU=gu; f.furGradV=gv; stream.Append(f); } o=a; o.pos=UnityWorldToClipPos(q0); o.ws=q0; o.screenPos=ComputeGrabScreenPos(o.pos); o.wireBary=float3(0,1,edgeSeed); UNITY_INITIALIZE_VERTEX_OUTPUT_STEREO(o); TRANSFER_SHADOW_WPOS(o,o.ws); { NXFinInput f; f.data=o; f.furGradU=gu; f.furGradV=gv; stream.Append(f); } o=b; o.pos=UnityWorldToClipPos(q1); o.ws=q1; o.screenPos=ComputeGrabScreenPos(o.pos); o.wireBary=float3(1,1,edgeSeed); UNITY_INITIALIZE_VERTEX_OUTPUT_STEREO(o); TRANSFER_SHADOW_WPOS(o,o.ws); { NXFinInput f; f.data=o; f.furGradU=gu; f.furGradV=gv; stream.Append(f); } stream.RestartStrip(); }\n");
            b.Append("[maxvertexcount(12)] void geomFurFin(triangle NXInput tri[3], inout TriangleStream<NXFinInput> stream, uint primitiveId : SV_PrimitiveID) { float3 gu,gv; float3 a=tri[1].ws-tri[0].ws,b=tri[2].ws-tri[0].ws; NX_FurUvGradients(a,b,tri[1].uv-tri[0].uv,tri[2].uv-tri[0].uv,normalize(cross(a,b)),gu,gv); NXInput input=tri[0]; float coverage=saturate((").Append(density).Append(")/100.0); float gate=step(NX_FurFinHash(float3(tri[0].uv+tri[1].uv+tri[2].uv,primitiveId)),coverage); if(gate>0) { NX_EmitFurFin(tri[0],tri[1],0,gu,gv,stream); NX_EmitFurFin(tri[1],tri[2],1,gu,gv,stream); NX_EmitFurFin(tri[2],tri[0],2,gu,gv,stream); } }\n");
            b.Append("float4 fragFurFin(NXFinInput fin):SV_Target { NXInput input=fin.data; UNITY_SETUP_STEREO_EYE_INDEX_POST_VERTEX(input); float2 strip=input.wireBary.xy; float edgeFade=smoothstep(0,.08+max(.001,").Append(thickness).Append("*.25),min(strip.x,1-strip.x)); float cells=max(1,abs(").Append(density).Append(")); float stripeCoord=strip.x*cells; float stripeLocal=frac(stripeCoord)-.5; float h=saturate(strip.y); float radius=max(.01,").Append(thickness).Append("*.5*pow(saturate(1-h),max(.001,").Append(Num(taper)).Append("))); float duty=saturate(radius*2); float footprint=max(fwidth(stripeCoord),.0001); float lo=stripeCoord-footprint*.5, hi=stripeCoord+footprint*.5; float lowIntegral=floor(lo)*duty+clamp(frac(lo)-(.5-duty*.5),0,duty); float highIntegral=floor(hi)*duty+clamp(frac(hi)-(.5-duty*.5),0,duty); float stripeMask=saturate((highIntegral-lowIntegral)/footprint); float tipFade=1-smoothstep(.82,1,h); float finStrand=edgeFade*stripeMask*tipFade*saturate(").Append(mask).Append("); float3 viewDir=normalize(_WorldSpaceCameraPos-input.ws); float3 normalSum=input.n; float normalLength=length(normalSum); float3 sourceNormal=normalLength>.001 ? normalSum/normalLength : float3(0,0,1); float grazing=smoothstep(.5,.95,1-abs(dot(sourceNormal,viewDir))); clip(finStrand*grazing-.001); float4 root=(").Append(rootColor).Append("); float4 tip=(").Append(tipColor).Append("); float4 c=lerp(root,tip,pow(h,max(.001,").Append(Num(taper)).Append("))); float3 n=sourceNormal; float3 lightDir=normalize(UnityWorldSpaceLightDir(input.ws)); float selfShadow=NX_FurSelfShadow(input,h,cells,").Append(thickness).Append(",").Append(Num(taper)).Append(",input.sourceUV.x,").Append(mask).Append(",lightDir,fin.furGradU,fin.furGradV); UNITY_LIGHT_ATTENUATION(sceneShadow,input,input.ws); float3 lit=max(0,ShadeSH9(float4(n,1)))+_LightColor0.rgb*saturate(dot(n,lightDir))*selfShadow*").Append(receiveShadows?"sceneShadow":"1").Append("; float rim=pow(saturate(1-dot(n,viewDir)),2)*").Append(Num(rimStrength)).Append("; return float4(c.rgb*(lit+rim),c.a*finStrand*grazing*").Append(Num(finOpacity)).Append("); }\nENDCG\n}\n");
            return b.ToString();
        }
    }
}
